### DISCUSSION TITLE
Line chart with data type Time (hh:mm:ss.00)

### DISCUSSION THREAD

**Discussion by danielwertheim** [evidence-dev/evidence#3133] [Q&A]
I have a DuckDB database with:
- `TimeTaken` of data type `Time`
- `TimeTakenMs` of data type `UBIGINT` (represents the same value but in milliseconds)
- `ObservationDate` of data type `Date`.

How are we supposed to use e.g. the LineChart to show these values over dates?

```
<LineChart 
    data={results_filtered1}
    x=ObservationDate
    y=TimeTaken
    yAxisTitle="Result"
    markers=true
    labels=true
/>
```

Will render everything on the same "level".

Using `TimeTakenMs` plots the values correctly but I can't find a way to then use the `TimeTaken` for display.

So given e.g.

```
entry1:
  ObservationDate: 2025-03-01
  TimeTaken: 00:12:13.14
entry2:
  ObservationDate: 2025-03-02
  TimeTaken: 00:10:09.00
```

How do I get that to properly display a line with two points?
