### ISSUE TITLE
Docker Images not working ?

### ISSUE THREAD

**Issue by accforgithubtest** [evidence-dev/evidence#1168]
I am looking to setup a docker compose based set up of evidence 
Not looking to have a dev environment, however could not find any non-development docker image, so using this development image.

Pls help to get this docker container working.

## Steps To Reproduce

Using below simple docker-compose.yaml

```
version: "3.7"
services:
  evidence:
    image: evidencedev/devenv:latest
    container_name: evidence
    init: true
    volumes:
      - ${pwd}:/evidence-workspace
    ports:
      - 3000
    depends_on:
      - db
    links:
      - db

# ..... rest is ignored for brevity
# db works fine as I have been able to connect to it using other applications.
```

### Environment

- Node version (`node -v`): N/A
- npm version (`npm -v`): N/A
- OS: Ubuntu LTS
- Browser: N/A
- Database: Mysql

## Expected Behavior

Docker image starts up without issues.

## Actual Behaviour

Container terminates / exits with below in logs

```
15/09/2023 10:32:25 am
Starting Evidence.dev development environment mounted on /evidence-workspace in the container.
15/09/2023 10:32:25 am
Provided arguments => 
15/09/2023 10:32:25 am
Running command => npm install && npm run dev -- --host 0.0.0.0
15/09/2023 10:32:26 am
15/09/2023 10:32:26 am
up to date, audited 1 package in 180ms
15/09/2023 10:32:26 am
15/09/2023 10:32:26 am
found 0 vulnerabilities
15/09/2023 10:32:27 am
npm ERR! Missing script: "dev"
15/09/2023 10:32:27 am
npm ERR! 
15/09/2023 10:32:27 am
npm ERR! To see a list of scripts, run:
15/09/2023 10:32:27 am
npm ERR!   npm run
15/09/2023 10:32:27 am
15/09/2023 10:32:27 am
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-14T21_32_27_003Z-debug-0.log
Container stopped
```
