### ISSUE TITLE
Project Level or Connector Config for Timezone Treatment

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1474]
E.g. do you want to present local timestamps on the client, and which tz your source

**Comment by ItsMeBrianD** [comment]
It's noteworthy that in the context of a `connection.yaml` file, the way we handle this will impact how it is specified in the connection.yaml

```yaml
name: myConnector
type: duckdb
### Anything else here is handled at the evidence (sdk) level

###
options:
  filename: ":memory:"
  ### Anything in options needs to be handled by the connector

```
