### ISSUE TITLE
Env vars used to configure production deploys are case sensitive, but documentation doesn't mention that

### ISSUE THREAD

**Issue by mmr-crexi** [evidence-dev/evidence#1578]
## Steps To Reproduce

Go to this page: https://docs.evidence.dev/cli#environment-variables

I would expect the env var to be case insensitive, all-caps, like what is displayed in the `export` command in bash on linux.  Instead, env vars appear to be case sensitive, as github CI deploys using `npm run source` as a CI check fails when env vars are all caps.

### Environment

github CI/CD using a makefile-based runner

## Expected Behavior

Env vars to be case insensitive all caps (not the _contents_ of the env var, just the name of the env var.

## Actual Behaviour

Env vars are case sensitive for the last two words (ie, SNOWFLAKE vs Snowflake)

## Workarounds

Just had to ask for help to get this solved.  Ideally either the docs are updated or the behavior is more in line with expectations (but my expectations are mine, so a docs fix is probably sufficient)

**Comment by archiewood** [comment]
Note that this can we worked around in some environments, such as github secrets like this
```yaml
    env:
          EVIDENCE_SOURCE__taxi__project_id: ${{ secrets.EVIDENCE_SOURCE__TAXI__PROJECT_ID }}
          EVIDENCE_SOURCE__taxi__client_email: ${{ secrets.EVIDENCE_SOURCE__TAXI__CLIENT_EMAIL }}
          EVIDENCE_SOURCE__taxi__private_key: ${{ secrets.EVIDENCE_SOURCE__TAXI__PRIVATE_KEY }}
```
