### ISSUE TITLE
Clickhouse connection not working - ClickHouse doesn't support extended query mechanism

### ISSUE THREAD

**Issue by slnw** [evidence-dev/evidence#1647]
## Steps To Reproduce

Source config:
```yaml
# This file was automatically generated
name: ch
type: postgres
options:
  connectionString: "postgresql://clickhouse:pass@localhost:9005/api?preferQueryMode=simple&sslmode=disable"
```

The connection works from terminal.
Also tried default pgres connection settings which doesn't work.
It's a pgres clickhouse interface

### Environment

- Node version (`node -v`): v20.11.1
- npm version (`npm -v`):10.2.4
- OS: mac
- Browser: chrome
- Database: clickhouse:24.1.5.6-alpine (latest at this time)

## Actual Behaviour

```bash
npm run sources

> my-evidence-project@0.0.1 sources
> evidence sources

Processing ch
ClickHouse doesn't support extended query mechanism
```
