### ISSUE TITLE
[Bug]: Themes - colorPalette with <10 values uses defaults for undefined values

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2893]
### Describe the bug

```yaml
theme:
  colorPalettes:
    default:
      light:
        - "#000000"  # Black
        - "#1A1A1A"  # 10% Gray
        - "#333333"  # 20% Gray
        - "#4D4D4D"  # 30% Gray
        - "#666666"  # 40% Gray
      dark:
        - "#FFFFFF"  # White
        - "#E6E6E6"  # 90% Gray
        - "#CCCCCC"  # 80% Gray
        - "#B3B3B3"  # 70% Gray
        - "#999999"  # 60% Gray
```

![Image](https://github.com/user-attachments/assets/5764eef3-b20d-4787-914a-d34259814c02)

### Steps to Reproduce

NA

### Logs

```Shell

```

### System Info

```Shell

```

### Severity

annoyance
