### ISSUE TITLE
[Docs]: Sample GitHub Actions for deploying to GitHub Pages might be wrong

### ISSUE THREAD

**Issue by omuomugin** [evidence-dev/evidence#2919]
### Request Type

Small Fix (wording, errors, typos, etc.)

### Description

As I followed [Deployment > GitHub Pages](https://docs.evidence.dev/deployment/github-pages/ ), the sample actions did not worked correctly.

I'm guessing `BASE_PATH` is not working as expected so that uploading artifact fails.
Sorry but I did not dig into implementation of cli yet.

```
- name: build
  env:
    BASE_PATH: '/${{ github.event.repository.name }}' # -> guessing this part is not working so that upload artifact part fails
    ## Add and uncomment any environment variables here
    ## EVIDENCE_SOURCE__my_source__username: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__USERNAME }}
    ## EVIDENCE_SOURCE__my_source__private_key: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__PRIVATE_KEY }}
  run: |
    npm run sources
    npm run build

- name: Upload Artifacts
uses: actions/upload-pages-artifact@v3
with:
    path: 'build/${{ github.event.repository.name }}' # -> fails for "directory not found"
```

Anyway this project is incredible and we are already planning to migrate our internal tools.

### Are you interested in contributing this improvement to the docs?

I'm just making a suggestion
