### ISSUE TITLE
[Bug]: Running `npm run sources` eats all my CPU and does not exit after 10 minutes

### ISSUE THREAD

**Issue by spinscale** [evidence-dev/evidence#3001]
### Describe the bug

I am trying to run `npm run sources` on a project with a single CSV file, that has 1.7 mio entries and 62 columns with a size of 483 MB. Unfortunately this eats all my CPUs on an M1 Pro, enables the fan immediately but I do not see any progress, even after running it for 10 minutes. Running `npm run sources -- --debug` does not tell my anything either except displaying `[Processing] ...` and then spinning up the fans.

Is there anything I can do to debug the issue? As the file is relatively small, loading 1.7 mio entries should IMO be done in a minute or two relatively easily, especially when using all the cores. I'd be happy to just ignore all errors and be good with it.

Happy for any pointers.

### Steps to Reproduce

Just ran `npm run sources` with the following configuration:

```
# This file was automatically generated
type: csv
name: stromspeicher
# Advanced Options, you probably don't want to change this
buildOptions:
  batchSize: 1000000
options:
  options: ignore_errors=true
```

### System Info

```Shell
I just created the project as mentioned in the docs, dependencies are


  "dependencies": {
    "@evidence-dev/bigquery": "^2.0.9",
    "@evidence-dev/core-components": "^5.0.3",
    "@evidence-dev/csv": "^1.0.14",
    "@evidence-dev/databricks": "^1.0.8",
    "@evidence-dev/duckdb": "^1.0.13",
    "@evidence-dev/evidence": "^40.0.3",
    "@evidence-dev/motherduck": "^1.0.4",
    "@evidence-dev/mssql": "^1.1.2",
    "@evidence-dev/mysql": "^1.1.4",
    "@evidence-dev/postgres": "^1.0.7",
    "@evidence-dev/snowflake": "^1.2.2",
    "@evidence-dev/sqlite": "^2.0.7",
    "@evidence-dev/trino": "^1.0.9"
  }


I am using node `v22.13.0`.
```

### Severity

blocking all usage of Evidence
