### ISSUE TITLE
[Bug]: Themes - Boxplot uses color primary not chart colorPalette as default

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#3082]
### Describe the bug

Actual

![Image](https://github.com/user-attachments/assets/542d86df-89b6-4e29-aee5-cca096baa3cc)

Should be 

![Image](https://github.com/user-attachments/assets/0c049330-defe-48d5-b336-d656a8e92016)

### Steps to Reproduce

See [docs](https://docs.evidence.dev/components/charts/box-plot/) 

The blue is too vibrant - it is using 

```
    primary:
      light: "#2563eb"
```

not 

```
  colorPalettes:
    default:
      light:
        - "#236aa4"
 ```
