### ISSUE TITLE
Add organized CSS color vars

### ISSUE THREAD

**Issue by yukseltron** [evidence-dev/evidence#501]
**Feature Description**
Colour variables are currently just the colour and a number (e.g. --yellow-400). This makes it hard to quickly implement new themes. Currently, all components seem to reference raw colour variables directly.

**Goal of Feature**
Adding a hierarchy for CSS colour variables is an important part of a design system. This allows for more readable/maintainable code and can be used to allow users to set their own (custom) themes.

**Proposed Solution**
We should organize the colour variables hierarchically, such as:
1. Raw (hexcodes, RGB)
2. Semantic (primary, secondary, etc)
3. Component (text-color, button-background, etc)

This way, we limit the usage of raw colour values, and instead, use semantic-based and component-based colour names. Consideration should be made to the naming schemes for these semantic-based and component-based tokens.

**Examples/Screenshots**
```CSS
:root {
    /* Raw */
    --white: #fff;
    
    /* Theme (Semantic) */
    --primary: var(--white);
    
    /* Component */
    --font-color: var(--primary)
}
```

**Are you interested in contributing this feature?**
Sure, I can contribute to this.
